#pragma once

enum CustomEvents
{
    EVENT_NONE,
    EVENT_BLE_CONNECTED,
    EVENT_BLE_DISCONNECT,
    EVENT_BLE_TRY_STOP_ADV,
    EVENT_BLE_TRY_START_ADV,
    EVENT_WIFI_PASS_RECEIVED,
    EVENT_WIFI_AZURE_KEY_RECEIVED,
    EVENT_WIFI_START_SCAN,
    EVENT_WIFI_SCAN_COMPLETED,
    EVENT_WIFI_TRY_CONNECT,
    EVENT_WIFI_CONNECTED,
    EVENT_WIFI_DISCONNECTED,
    EVENT_GOOGLE_HOME_TRY_CONNECT,
    EVENT_GOOGLE_HOME_CONNECTED,
    EVENT_GOOGLE_REPORT_TEMPERATURE,
    EVENT_GOOGLE_REPORT_HUMIDITY,
    EVENT_GOOGLE_REPORT_AIR_QUALITY,
    EVENT_GOOGLE_REPORT_PRESSURE,
    EVENT_AZURE_IOT_HUB_TRY_CONNECT,
    EVENT_AZURE_IOT_HUB_CONNECTED,
    EVENT_AZURE_IOT_HUB_DISCONNECTED,
    EVENT_NODE_DEVICE_LOCATION,
    EVENT_NODE_USER_NAME,
    EVENT_FACTORY_RESET,
    EVENT_FACTORY_RESET_SAFE,
    EVENT_RESTART,
};

enum Languages
{
    English,
    Deutsch,
    NotSupported
};

enum AzureKeys
{
    Temperature,
    Humidity,
    Pressure,
    AirQuality
};