#pragma once

enum CustomEvents
{
    EVENT_NONE,
    EVENT_BLE_CONNECTED,
    EVENT_BLE_DISCONNECT,
    EVENT_BLE_TRY_STOP_ADV,
    EVENT_BLE_TRY_START_ADV,
    EVENT_WIFI_PASS_RECEIVED,
    EVENT_WIFI_AZURE_KEY_RECEIVED,
    EVENT_WIFI_START_SCAN,
    EVENT_WIFI_SCAN_COMPLETED,
    EVENT_WIFI_TRY_CONNECT,
    EVENT_WIFI_CONNECTED,
    EVENT_WIFI_DISCONNECTED,
    EVENT_GOOGLE_HOME_TRY_CONNECT,
    EVENT_GOOGLE_HOME_CONNECTED,
    EVENT_GOOGLE_REPORT_TEMPERATURE,
    EVENT_GOOGLE_REPORT_HUMIDITY,
    EVENT_GOOGLE_REPORT_AIR_QUALITY,
    EVENT_GOOGLE_REPORT_PRESSURE,
    EVENT_GOOGLE_REPORT_TEMPERATURE_SUMMARY,
    EVENT_GOOGLE_REPORT_HUMIDITY_SUMMARY,
    EVENT_GOOGLE_REPORT_AIR_QUALITY_SUMMARY,
    EVENT_GOOGLE_REPORT_PRESSURE_SUMMARY,
    EVENT_AZURE_IOT_HUB_TRY_CONNECT,
    EVENT_AZURE_IOT_HUB_CONNECTED,
    EVENT_AZURE_IOT_HUB_DISCONNECTED,
    EVENT_NODE_DEVICE_LOCATION,
    EVENT_NODE_USER_NAME,
    EVENT_FACTORY_RESET,
    EVENT_FACTORY_RESET_SAFE,
    EVENT_RESTART,
};

enum DisplayStatus
{
    TemperatureSensor,
    HumiditySensor,
    PressureSensor,
    AirQualitySensor,
    AllSensors,
    Time
};

enum Languages
{
    English,
    Deutsch,
    Francais,
    NotSupported
};

enum AzureKeys
{
    Temperature,
    Humidity,
    Pressure,
    AirQuality,
    Summary,
    Report
};

enum SensorType
{
    No_Sensor,
    BMP280_Sensor,
    BME280_Sensor,
    BME680_Sensor
};

enum SensorCalibrationStatus
{
    UNRELIABLE = 0,
    LOW_ACCURACY = 1,
    MEDIUM_ACCURACY = 2,
    HIGH_ACCURACY = 3

};